Repository climbing-size-matters/climbing-size-matters, pull requests merged in 2025-04, with the labels that each got.

#22 Fix pre commit
  .husky/pre-commit
  package.json
Labels: bug, tools

#24 Build and test workflow
  .github/pull_request_template.md
  .github/workflows/build-and-test.yaml
  package.json
Labels: tools

#21 Model data
  src/cam-database/brands.ts
  src/cam-database/cams.ts
  src/cam-database/database.ts
  src/cam-database/models.ts
  src/cam-database/types.ts
  src/entrypoints/content/highlight-cam-objects.ts
  src/entrypoints/content/index.ts
  test/entrypoints/content/highlight-gear.spec.ts
Labels: enhancement
